import { jsPDF } from 'jspdf';

/**
 * Generate and download a PDF report of today's productivity data.
 */
export function generatePDF(data, microConfig) {
  try {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    // Title
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('Productivity Enforcer - Daily Report', pageWidth / 2, y, { align: 'center' });
    y += 12;

    // Date
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Date: ' + (data.date || new Date().toISOString().slice(0, 10)), pageWidth / 2, y, { align: 'center' });
    y += 16;

    // Separator
    doc.setDrawColor(200);
    doc.line(20, y, pageWidth - 20, y);
    y += 12;

    // Macro Tasks
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Macro Tasks', 20, y);
    y += 10;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const macroTasks = data.macroTasks || [];
    if (macroTasks.length === 0) {
      doc.text('No macro tasks recorded.', 24, y);
      y += 8;
    } else {
      macroTasks.forEach(task => {
        const status = task.done ? '[x]' : '[ ]';
        doc.text(status + '  ' + (task.text || ''), 24, y);
        y += 7;
      });
    }
    y += 8;

    // Pomodoro Sessions
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Pomodoro Sessions', 20, y);
    y += 10;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text('Sessions completed: ' + (data.pomodoroSessions || 0), 24, y);
    y += 12;

    // Micro Tasks
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Micro Tasks (Daily Habits)', 20, y);
    y += 10;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const configs = microConfig || [];
    if (configs.length === 0) {
      doc.text('No micro tasks configured.', 24, y);
      y += 8;
    } else {
      configs.forEach(task => {
        const done = (data.microStatus || {})[task.id] || false;
        const status = done ? '[x]' : '[ ]';
        doc.text(status + '  ' + (task.text || ''), 24, y);
        y += 7;
      });
    }
    y += 8;

    // Enforcer Logs
    const logs = data.enforcerLogs || [];
    if (logs.length > 0) {
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text('Enforcer Logs', 20, y);
      y += 10;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      logs.forEach(log => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        doc.text('[' + (log.timestamp || '') + ']', 24, y);
        y += 5;
        const lines = doc.splitTextToSize(log.text || '', pageWidth - 48);
        lines.forEach(line => {
          doc.text(line, 28, y);
          y += 5;
        });
        y += 4;
      });
    }

    // Footer
    y = doc.internal.pageSize.getHeight() - 15;
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text('Generated by Productivity Enforcer', pageWidth / 2, y, { align: 'center' });

    // Download
    doc.save('productivity_' + (data.date || 'report') + '.pdf');
  } catch (err) {
    console.error('PDF generation failed:', err);
    alert('Failed to generate PDF. Check console for details.');
  }
}
